### ISSUE TITLE
Add some nice css for scrollbar

### ISSUE THREAD

**Issue by GoodGameRuler** [GoodGameRuler/unitrack_v3#14]
Make nice css from scrollbar for chrome, safari and mozilla

Safari
```css
    ::-webkit-scrollbar {
        height: 8px;              /* height of horizontal scrollbar ← You're missing this */
        width: 8px;               /* width of vertical scrollbar */
        background: rgba(26, 32, 34, 0.9);;
    }

    ::-webkit-scrollbar-thumb:active {
        background: #FFFFFF;
    }

    ::-webkit-scrollbar-thumb{
        background: #295968;
        border-radius: 10px;
    }
```
Mozilla
```css
    @-moz-document url-prefix(){
        body {
            scrollbar-width: 4px;
            scrollbar-color: #295968 rgba(26, 32, 34, 0.9);
        }
    }
```
